sudo: false
language: java
dist: trusty
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
install: true
addons:
  sonarcloud:
    organization: xdean-github
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: 
- mvn clean package sonar:sonar -P jacoco
after_success:
- bash <(curl -s https://codecov.io/bash)